from io import BytesIO
from datetime import datetime
from pathlib import Path
import re
import html

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, KeepTogether


class PDFGenerator:

    LEFT_MARGIN = 24
    RIGHT_MARGIN = 24
    TOP_MARGIN = 58
    BOTTOM_MARGIN = 42

    @staticmethod
    def _get_logo_path():
        current_file = Path(__file__).resolve()

        candidates = [
            current_file.parents[2] / "assets" / "study-logo.png",
            current_file.parents[1] / "assets" / "study-logo.png",
            current_file.parent / "assets" / "study-logo.png",
        ]

        for path in candidates:
            if path.exists() and path.is_file():
                return path

        return None

    @staticmethod
    def _clean_text(value):
        if value is None:
            return ""

        text = str(value).replace("\r\n", "\n").replace("\r", "\n")
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n[ \t]+", "\n", text)

        text = re.sub(
            r"(?m)^\s*[-*•]\s+",
            "• ",
            text,
        )

        return text.strip()

    @staticmethod
    def _escape_text(value):
        return html.escape(str(value), quote=False)

    @staticmethod
    def _draw_page(canvas, document):
        canvas.saveState()

        page_width, page_height = A4
        page_number = canvas.getPageNumber()

        canvas.setStrokeColor(colors.HexColor("#0F62FE"))
        canvas.setLineWidth(2)
        canvas.line(
            PDFGenerator.LEFT_MARGIN,
            page_height - 40,
            page_width - PDFGenerator.RIGHT_MARGIN,
            page_height - 40,
        )

        canvas.setFont("Helvetica-Bold", 9)
        canvas.setFillColor(colors.HexColor("#0F62FE"))
        canvas.drawString(
            PDFGenerator.LEFT_MARGIN,
            page_height - 27,
            "StudyFlow AI",
        )

        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#667085"))
        canvas.drawString(
            PDFGenerator.LEFT_MARGIN,
            page_height - 18,
            "AI Powered Smart Learning Management System",
        )

        logo_path = PDFGenerator._get_logo_path()

        if logo_path:
            try:
                from reportlab.lib.utils import ImageReader

                logo_width = 0.85 * inch
                logo_height = 0.48 * inch

                canvas.drawImage(
                    ImageReader(str(logo_path)),
                    page_width - PDFGenerator.RIGHT_MARGIN - logo_width,
                    page_height - 37 - logo_height,
                    width=logo_width,
                    height=logo_height,
                    preserveAspectRatio=True,
                    mask="auto",
                )
            except Exception:
                pass

        canvas.setStrokeColor(colors.HexColor("#E5E7EB"))
        canvas.setLineWidth(0.7)
        canvas.line(
            PDFGenerator.LEFT_MARGIN,
            29,
            page_width - PDFGenerator.RIGHT_MARGIN,
            29,
        )

        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#98A2B3"))

        canvas.drawString(
            PDFGenerator.LEFT_MARGIN,
            17,
            "Confidential - Generated by StudyFlow AI",
        )

        canvas.drawRightString(
            page_width - PDFGenerator.RIGHT_MARGIN,
            17,
            f"Page {page_number}",
        )

        canvas.restoreState()

    @staticmethod
    def _build_content_flowable(line, styles):
        """
        Turns a single logical line (bullet / numbered / plain) into the
        Paragraph flowable that represents it, using the correct style.
        Returns (flowable, trailing_spacer_height).
        """
        if line.startswith("•"):
            bullet_text = line[1:].strip()
            return (
                Paragraph(
                    PDFGenerator._escape_text(bullet_text),
                    styles["Bullet"],
                    bulletText="•",
                ),
                3,
            )

        numbered = re.match(r"^(\d+)\.\s+(.*)$", line)

        if numbered:
            number = numbered.group(1)
            item_text = numbered.group(2)

            return (
                Paragraph(
                    PDFGenerator._escape_text(item_text),
                    styles["Numbered"],
                    bulletText=f"{number}.",
                ),
                3,
            )

        return (
            Paragraph(
                PDFGenerator._escape_text(line),
                styles["Body"],
            ),
            4,
        )

    @staticmethod
    def _make_field(key, value, styles):
        field_name = (
            str(key)
            .replace("_", " ")
            .strip()
            .title()
        )

        clean_value = PDFGenerator._clean_text(value)

        heading = Paragraph(field_name, styles["FieldHeading"])

        if not clean_value:
            # Heading + its only content ("N/A") must never be split apart.
            return [
                KeepTogether([
                    heading,
                    Spacer(1, 4),
                    Paragraph("N/A", styles["Body"]),
                ]),
                Spacer(1, 12),
            ]

        lines = clean_value.split("\n")

        result = []
        # Content that still needs to be glued to the heading so the
        # heading never gets orphaned alone at the bottom of a page.
        pending_group = [heading, Spacer(1, 4)]
        heading_attached = False

        for raw_line in lines:
            line = raw_line.strip()

            if not line:
                # Blank line: safe to let it fall on its own, it carries
                # no content that could be "cut in half".
                if heading_attached:
                    result.append(Spacer(1, 5))
                else:
                    pending_group.append(Spacer(1, 5))
                continue

            content_flowable, trailing_space = PDFGenerator._build_content_flowable(
                line, styles
            )

            if not heading_attached:
                # First real content line: keep heading + this paragraph
                # together as a single unbreakable unit.
                pending_group.append(content_flowable)
                pending_group.append(Spacer(1, trailing_space))
                result.append(KeepTogether(pending_group))
                heading_attached = True
            else:
                # Every subsequent paragraph is its own atomic unit: it
                # will move to the next page as a whole rather than being
                # sliced across the page boundary.
                result.append(
                    KeepTogether([
                        content_flowable,
                        Spacer(1, trailing_space),
                    ])
                )

        result.append(Spacer(1, 14))
        return result

    @staticmethod
    def generate(report: dict, report_type: str) -> BytesIO:
        buffer = BytesIO()

        document = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=PDFGenerator.LEFT_MARGIN,
            rightMargin=PDFGenerator.RIGHT_MARGIN,
            topMargin=PDFGenerator.TOP_MARGIN,
            bottomMargin=PDFGenerator.BOTTOM_MARGIN,
            title=f"StudyFlow AI - {report_type} Report",
            author="StudyFlow AI",
        )

        base = getSampleStyleSheet()

        styles = {
            "Title": ParagraphStyle(
                "StudyFlowTitle",
                parent=base["Title"],
                fontName="Helvetica-Bold",
                fontSize=21,
                leading=25,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#101828"),
                spaceAfter=5,
            ),
            "Subtitle": ParagraphStyle(
                "StudyFlowSubtitle",
                parent=base["Normal"],
                fontSize=9.5,
                leading=13,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#667085"),
            ),
            "Normal": ParagraphStyle(
                "StudyFlowNormal",
                parent=base["Normal"],
                fontSize=8.8,
                leading=13,
                textColor=colors.HexColor("#344054"),
            ),
            "FieldHeading": ParagraphStyle(
                "StudyFlowFieldHeading",
                parent=base["Heading3"],
                fontName="Helvetica-Bold",
                fontSize=11,
                leading=15,
                alignment=TA_LEFT,
                textColor=colors.HexColor("#0F62FE"),
                keepWithNext=True,
            ),
            "Body": ParagraphStyle(
                "StudyFlowBody",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=9.2,
                leading=14,
                alignment=TA_LEFT,
                textColor=colors.HexColor("#273444"),
                wordWrap="LTR",
                splitLongWords=True,
                allowWidows=False,
                allowOrphans=False,
                spaceAfter=4,
            ),
            "Bullet": ParagraphStyle(
                "StudyFlowBullet",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=9.2,
                leading=14,
                alignment=TA_LEFT,
                textColor=colors.HexColor("#273444"),
                leftIndent=15,
                firstLineIndent=-10,
                wordWrap="LTR",
                splitLongWords=True,
                allowWidows=False,
                allowOrphans=False,
            ),
            "Numbered": ParagraphStyle(
                "StudyFlowNumbered",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=9.2,
                leading=14,
                alignment=TA_LEFT,
                textColor=colors.HexColor("#273444"),
                leftIndent=21,
                firstLineIndent=-17,
                wordWrap="LTR",
                splitLongWords=True,
                allowWidows=False,
                allowOrphans=False,
            ),
            "Footer": ParagraphStyle(
                "StudyFlowFooter",
                parent=base["Italic"],
                fontSize=8,
                leading=11,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#98A2B3"),
            ),
        }

        elements = []

        # Report title
        elements.append(Spacer(1, 0.08 * inch))
        elements.append(
            Paragraph(
                f"{PDFGenerator._escape_text(report_type)} Report",
                styles["Title"],
            )
        )
        elements.append(
            Paragraph(
                "AI Powered Smart Learning Management System",
                styles["Subtitle"],
            )
        )
        elements.append(Spacer(1, 0.12 * inch))

        # Meta
        elements.append(
            Paragraph(
                f"<b>Generated On:</b> "
                f"{datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
                styles["Normal"],
            )
        )
        elements.append(
            Paragraph(
                f"<b>Report Type:</b> "
                f"{PDFGenerator._escape_text(report_type)}",
                styles["Normal"],
            )
        )
        elements.append(Spacer(1, 0.16 * inch))

        # Content:
        # No giant Table is used. Each field, and each paragraph within
        # a field, is wrapped in its own KeepTogether flowable, so
        # ReportLab is never allowed to slice a paragraph in half across
        # a page boundary — a paragraph either fits on the current page
        # in full, or moves to the next page in full.
        report_rows = list(report.items())

        if not report_rows:
            elements.append(
                Paragraph(
                    "No report data available.",
                    styles["Body"],
                )
            )
        else:
            for key, value in report_rows:
                elements.extend(
                    PDFGenerator._make_field(
                        key,
                        value,
                        styles,
                    )
                )

        elements.append(Spacer(1, 0.08 * inch))
        elements.append(
            Paragraph(
                "This report is automatically generated by "
                "<b>StudyFlow AI</b>.",
                styles["Footer"],
            )
        )

        document.build(
            elements,
            onFirstPage=PDFGenerator._draw_page,
            onLaterPages=PDFGenerator._draw_page,
        )

        buffer.seek(0)
        return buffer


def test_with_ai_text():
    report = {
        "student_name": "John Doe",
        "course": "Machine Learning Fundamentals",
        "notes_summary": """
Building systems that learn from data and adapt to new information automatically without human intervention.

This is a key concept in AI that enables machines to improve their performance over time.

""" + ("Loop that processes microtasks and macrotasks to deliver non-blocking performance. " * 6) + """

Syntactically, it supports multiple paradigms - procedural, functional (via first-class functions and closures), and object-oriented (via prototypal inheritance, abstractly represented by class syntax).

As a developer, mastery requires a deep understanding of memory concepts (closures, scope) and the event-driven, non-blocking I/O model that makes it so effective for building scalable network applications.
""",
        "key_concepts": """
• Supervised Learning
• Unsupervised Learning
• Reinforcement Learning
• Deep Learning
""",
        "topics_covered": """
1. Introduction to AI
2. Machine Learning Basics
3. Neural Networks
4. Deep Learning
""",
        "feedback": """
Excellent progress! The student has demonstrated strong understanding of core concepts and can apply them to real-world problems effectively.

Key strengths:
• Strong analytical skills
• Good problem-solving ability
• Excellent understanding of algorithms
""",
    }

    try:
        pdf_bytes = PDFGenerator.generate(
            report,
            "Learning Progress",
        )

        with open("ai_generated_report.pdf", "wb") as file:
            file.write(pdf_bytes.getvalue())

        print("PDF generated successfully!")
        print("Saved as: ai_generated_report.pdf")
        return pdf_bytes

    except Exception as error:
        print(f"Error generating PDF: {error}")

        import traceback
        traceback.print_exc()
        return None


if __name__ == "__main__":
    test_with_ai_text()