"""create_course_resources_table

Revision ID: c3cc311b5a6a
Revises: d0d60253772c
Create Date: 2026-07-31 15:42:32.082689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cc311b5a6a'
down_revision: Union[str, Sequence[str], None] = 'd0d60253772c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_resources_course_name'), 'course_resources', ['course_name'], unique=False)
    op.create_index(op.f('ix_course_resources_id'), 'course_resources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_resources_id'), table_name='course_resources')
    op.drop_index(op.f('ix_course_resources_course_name'), table_name='course_resources')
    op.drop_table('course_resources')
    # ### end Alembic commands ###
